"""outbox

Revision ID: 17504d0dcfdd
Revises: 0f145551658f
Create Date: 2026-09-03 12:49:38.113004
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "17504d0dcfdd"
down_revision: str | None = "0f145551658f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox")),
    )
    with op.batch_alter_table("outbox", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_outbox_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_outbox_event_type"), ["event_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_outbox_published_at"), ["published_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("outbox", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_outbox_published_at"))
        batch_op.drop_index(batch_op.f("ix_outbox_event_type"))
        batch_op.drop_index(batch_op.f("ix_outbox_created_at"))

    op.drop_table("outbox")
    # ### end Alembic commands ###
